/**
 * PORTFOLIO INTELLIGENCE ENGINE (PIE) - FOUNDATION TYPES
 *
 * This file serves as the core type registry and structural contract for the
 * PIE modular architecture. It defines only contracts, schemas, and interfaces,
 * separating data contracts from runtime implementations.
 */

// ============================================================================
// 1. KNOWLEDGE REPRESENTATION
// ============================================================================

/**
 * Why it exists: Normalizes frontmatter fields from markdown knowledge documents.
 * Who owns it: Content / Asset Management Layer.
 * Who consumes it: Loader Service (extracts it) and Retriever Service (uses tags/priority for scoring).
 * Future extension points: Add schema validation metadata, access control groups, or multi-language locales.
 */
export interface IKnowledgeMetadata {
  title: string;
  category: string; // e.g., "projects", "experience", "skills", "bio"
  tags: string[];
  priority: 'high' | 'medium' | 'low';
  description?: string;
  [key: string]: any; // Allows custom metadata keys for future proofing
}

export interface IContentSection {
  heading: string; // The section heading (e.g. "Technical Stack")
  level: number; // The level of the heading (e.g., 2 for "##")
  content: string; // The text content under this heading
}

/**
 * Why it exists: Represents a single unit of parsed knowledge.
 * Who owns it: Knowledge Loader.
 * Who consumes it: Retriever (analyzes keywords/tags) and Prompt Composer (renders body text).
 * Future extension points: Add content type markers (e.g. Code vs Text) or relations/links to other IContentDocuments (graphs).
 */
export interface IContentDocument {
  id: string; // Unique document path identifier (e.g., "projects/aeroflare")
  title: string;
  type: string;
  schemaVersion: string;
  rawContent: string; // Cleaned markdown text body excluding frontmatter
  metadata: IKnowledgeMetadata;
  sections: IContentSection[]; // Logical sections split by markdown headings
  hash: string; // Document signature for caching and sync verification
}

// ============================================================================
// 2. CONVERSATION AND MESSAGING
// ============================================================================

export type MessageRole = 'system' | 'user' | 'assistant';

/**
 * Why it exists: Defines a message payload schema independent of LLM providers.
 * Who owns it: Chat State / UI Layer.
 * Who consumes it: Copilot Panel UI (displays bubbles) and Prompt Composer (structures completion parameters).
 * Future extension points: Add media attachment URIs, tokens count cache, or detailed sentiment tags.
 */
export interface IMessage {
  id: string;
  role: MessageRole;
  content: string;
  timestamp: number;
  actions?: IAction[]; // Structured actions generated by the AI for client-side side-effects
}

// ============================================================================
// 3. RETRIEVAL AND RANKING
// ============================================================================

/**
 * Why it exists: Represents retrieved knowledge matched against user queries with metrics.
 * Who owns it: Retriever Module.
 * Who consumes it: Prompt Composer (filters top results to inject in system prompt).
 * Future extension points: Add vector distance metrics, dense/sparse hybrid search score balances, or source chunk coordinates.
 */
export interface IRetrievedDocument {
  document: IContentDocument;
  score: number; // Relevance score (normalized 0.0 - 1.0)
  reason?: string; // Retrieval explanation for debugging
  matchExplanation?: {
    keywordsMatched: string[];
    metadataHits: number;
  };
}

/**
 * Why it exists: Formats a source document chunk into a standardized injection block for system prompts.
 * Who owns it: Prompt Composer Module.
 * Who consumes it: API Route Controller / LLM client.
 * Future extension points: Add citation format configurations (APA, IEEE, markdown link formats).
 */
export interface IContextBlock {
  sourceId: string;
  header: string;
  formattedText: string;
}

// ============================================================================
// 4. PROMPT ASSEMBLY
// ============================================================================

/**
 * Why it exists: Decouples LLM configurations from route handlers.
 * Who owns it: LLM Client Service.
 * Who consumes it: OpenRouter API service client.
 * Future extension points: Add routing parameters, fallback models, top-p, frequency penalties, or system safety thresholds.
 */
export interface ILLMConfig {
  model: string;
  temperature: number;
  maxTokens?: number;
  stream?: boolean;
}

/**
 * Why it exists: Houses the compiled payload sent to the LLM completion engine.
 * Who owns it: Prompt Composer Module.
 * Who consumes it: Route handler / LLM service client.
 * Future extension points: Support for system instructions formatting overrides, function declaration arrays (tool calling).
 */
export interface IPromptPayload {
  systemPrompt: string;
  messages: IMessage[];
  config: ILLMConfig;
}

// ============================================================================
// 5. CONVERSATION MEMORY
// ============================================================================

/**
 * Why it exists: Provides an interface for managing chat message histories and context limits.
 * Who owns it: Memory Management Layer.
 * Who consumes it: Route Controller / Prompt Composer (fetches historical context before calling LLM).
 * Future extension points: Persistence adapters (local storage, database tables, summary memory generators).
 */
export interface IConversationMemory {
  /**
   * Returns a pruned history of messages fitting under a character/token budget.
   */
  getPrunedHistory(messages: IMessage[], tokenLimit: number): Promise<IMessage[]>;
  
  /**
   * Estimates token consumption for a given string block.
   */
  estimateTokens(text: string): number;
}

// ============================================================================
// 6. ACTIONS AND TOOL EXECUTION
// ============================================================================

export type ActionType = 'FILE_OPEN' | 'NAVIGATE' | 'TERMINAL_SUGGESTION' | 'CUSTOM';

/**
 * Why it exists: Represents client-side actions triggered by the AI assistant response.
 * Who owns it: Action Parser Module.
 * Who consumes it: Copilot Panel UI / AppLayout component.
 * Future extension points: Execution handlers, action security confirmation modals, or chaining actions.
 */
export interface IAction {
  id: string;
  type: ActionType;
  payload: {
    target: string; // Target path or file key (e.g. "projects.js", "/contact")
    params?: Record<string, any>;
  };
}

// ============================================================================
// 7. GITHUB SYNCHRONIZATION (Future)
// ============================================================================

/**
 * Why it exists: Maps a repository resource to a local knowledge base markdown file.
 * Who owns it: Sync Service.
 * Who consumes it: Git Sync Worker Cron Job.
 * Future extension points: Webhook verification tokens, branch filters, or content translation templates.
 */
export interface ISyncTarget {
  repoUrl: string;
  branch: string;
  filePath: string;
  localDocId: string;
}

/**
 * Why it exists: Reports status and results of sync jobs.
 * Who owns it: Sync Service.
 * Who consumes it: Dashboard Admin Console / Log Services.
 * Future extension points: Slack/Discord notification payloads, sync histories, or roll-back triggers.
 */
export interface ISyncResult {
  target: ISyncTarget;
  status: 'SUCCESS' | 'FAILED' | 'SKIPPED_NO_CHANGE';
  syncedAt: number;
  error?: string;
  hashBefore?: string;
  hashAfter?: string;
}

// ============================================================================
// 8. CACHING STRATEGY
// ============================================================================

/**
 * Why it exists: Envelops cached data with timestamps and expiration rules.
 * Who owns it: Cache Service.
 * Who consumes it: Cache Storage layer.
 * Future extension points: Add tags for cache invalidation cascades or hit/miss statistic trackers.
 */
export interface ICacheEntry<T> {
  key: string;
  value: T;
  cachedAt: number;
  expiresAt?: number;
}

/**
 * Why it exists: Defines cache interface matching SOLID's Interface Segregation.
 * Who owns it: Platform Infrastructure Layer.
 * Who consumes it: Loader Service, Retriever Module, and API routes.
 * Future extension points: Redis connection pools, localStorage adapters, or service-worker caching proxies.
 */
export interface ICacheService {
  get<T>(key: string): Promise<T | null>;
  set<T>(key: string, value: T, ttlSeconds?: number): Promise<void>;
  delete(key: string): Promise<void>;
  clear(): Promise<void>;
}
